### ISSUE TITLE
Reconciled map to do list

### ISSUE THREAD

**Issue by alykat** [nprapps/usda-plant-hardiness#31]
Diagrams and notes in this markdown file:
https://github.com/nprapps/usda-plant-hardiness/blob/main/maps.md

- [x] Set up environment for map dev work (see Chris Amico's example from NICAR) #57 
- [x] Convert plant hardiness layers to PMTiles #35 
- [x] National temperature data as raster or vector?
- [x] Initial download of national OSM file #36 
- [x] Filter OSM data and convert to PMTiles (if necessary / depends on size)
- [x] Style temperature layers (USDA plant hardiness)
- [x] Upload everything to S3 — @brentajones?
